[Variables]
UserID=398355278
UserID2=14779707
UserID3=284370870
UserID4=47213089
UserID5=
Link=http://twitter.com/Mr_Random100
URL1=http://feeds.feedburner.com/designfollow/KmFf
URL2=http://www.feedzilla.com/rss/technology/computers
URL3=http://www.feedzilla.com/rss/society/rights-human-rights
UserName=UserName
Password=Password
WeatherCode=HUXX0019
Unit=m
ImagePath=C:\Documents and Settings\Rébék Benõ\Dokumentumok\gaia09\nature
Update=20000
